// This file defines the ICustomer interface, which extends the Mongoose Document interface. It represents the structure of a customer document in the MongoDB database, including fields for id, name, email, and phone.
//customerModel
//customer.model
import { Document,Schema } from "mongoose";
import { model } from "mongoose";

interface ICustomer extends Document {
  //  id: number; automatically generated by MongoDB, so we don't need to define it here
    id: string; // Define the id field as a string, which will be the unique identifier for each customer document
    name: string;
    age: number;
    isAdmin: boolean;
    email?: string;
}

const customerSchema = new Schema<ICustomer>({ // generic type parameter <ICustomer> is used to specify the type of 
    id: { type: String, required: true, unique: true }, // Define the id field as a string, required, and unique. 
    // This means that each customer document must have a unique id value, and it cannot be null or undefined. 
    // The unique constraint ensures that no two customer documents can have the same id value in the MongoDB collection.
    // documents that will be stored in the "Customer" collection
    name: { type: String, required: true },// use mongoDB data types to define the schema 
    // for the customer collection. The name field is defined as a string and is required, 
    // meaning that it must be provided when creating a new customer document.
    age: { type: Number, required: true },
    isAdmin: { type: Boolean, required: true },
    email: { type: String }
});

export const customerModel = model<ICustomer>("Customer", customerSchema); // Create a Mongoose model named "Customer" using the customerSchema. 
// The generic type parameter <ICustomer> is used to specify the type of documents that will be stored in the "Customer" collection. This model provides an interface for interacting with the MongoDB collection, allowing you to perform CRUD operations on customer documents.

